name-template: 'vNext'
tag-template:  'vNext'

branches:
  - main

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

change-title-escapes: '\\<*_&'

no-changes-template: '- No changes since last release'

category-template: '### $TITLE'
categories:
  - title: 'âœ¨ Features'
    labels:
      - enhancement
      - feature
  - title: 'ðŸ› Bug Fixes'
    labels:
      - bug
      - fix
  - title: 'âš¡ Performance Improvements'
    labels:
      - perf
  - title: 'â™»ï¸ Refactoring'
    labels:
      - refactor
  - title: 'ðŸ§ª Tests'
    labels:
      - test
  - title: 'ðŸ“š Documentation'
    labels:
      - docs
  - title: 'ðŸ›  Maintenance'
    labels:
      - chore
      - ci
      - build
  - title: 'ðŸ”„ Reverts'
    labels:
      - revert

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

template: |
  $CHANGES
